coverage:
  status:
    project: true
comment:
  layout: header, diff, flags, components
component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
      - type: patch
  individual_components:
    - component_id: pgmcli
      name: pgmcli
      paths:
        - packages/pgmcli/**
